import appclient.AppClient;
import appserver.AppServer;
import interfaces.IClient;
import interfaces.IServer;
/*
 * TestForm.java
 *
 * Created on 12 March 2007, 20:05
 */

/**
 *
 * @author  Roger
 */
public class TestForm extends javax.swing.JFrame {
    private IServer appServer;
    private IClient appClient;
    private boolean init;

//    String []args;
    private String title1, title2;
    
    /** Creates new form TestForm */
    public TestForm(String []args) {
        initComponents();
        /////////////////////////////////
        title1 = "AppStandaloneSys:  Mode ="; 
        title2 = "Spinners Concurrent Threads: v5 070311";

        //Activate the Server and the Client i.e. the MVC system
        appServer = new AppServer();
        appClient = new AppClient(args, appServer);

        setSize(250,600);    //**Initial size
        init = true;
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        startB = new javax.swing.JButton();
        theGUIPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        startB.setText("Start");

        org.jdesktop.layout.GroupLayout theGUIPanelLayout = new org.jdesktop.layout.GroupLayout(theGUIPanel);
        theGUIPanel.setLayout(theGUIPanelLayout);
        theGUIPanelLayout.setHorizontalGroup(
            theGUIPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 297, Short.MAX_VALUE)
        );
        theGUIPanelLayout.setVerticalGroup(
            theGUIPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 146, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(35, 35, 35)
                        .add(startB))
                    .add(layout.createSequentialGroup()
                        .add(25, 25, 25)
                        .add(theGUIPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(59, 59, 59)
                .add(theGUIPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 18, Short.MAX_VALUE)
                .add(startB)
                .add(54, 54, 54))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(final String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestForm(args).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton startB;
    private javax.swing.JPanel theGUIPanel;
    // End of variables declaration//GEN-END:variables
    
}
