/*
 * LinkclientSuite.java
 * JUnit based test
 *
 * Created on 24 November 2006, 13:51
 */

package linkclient;

import junit.framework.*;

/**
 *
 * @author Roger
 */
public class LinkclientSuite extends TestCase {
    
    public LinkclientSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("LinkclientSuite");
//        suite.addTest(linkclient.SimpleClientCommandTest.suite());
//        suite.addTest(linkclient.AppServerTest.suite());
        return suite;
    }
    
}
